### ISSUE TITLE
S3GetTask 404 Errors

### ISSUE THREAD

**Issue by wiicode** [corley-archive/aws-ant-task#27]
I am struggling with trying to get S3Get to work.   I get as far as this process:

dist:
    [s3get] Downloading 'build-cssdk/win-pthreads.zip' to 'dist'
    [s3get] Using credentials from ant build file
    [s3get] Region s3.amazonaws.com provided

So far I've compiled the latest aws-ant-tasks-0.5-SNAPSHOT.jar and tried using it.   Cannot download from my bucket. 

Made one change to try to troubleshoot.

```
 <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
        <version>1.8.4</version>
```

Not a Maven/Java coder, so fumbling through.

AmazonS3Exception: Status Code: 404, AWS Service: Amazon S3, AWS Request ID: HIDDEN_FROM_THIS_POST, AWS Error Code: null, AWS Error Message: Not Found, S3 Extended Request ID:  HIDDEN_FROM_THIS_POST
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:679)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:350)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:202)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3001)
    at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:801)
    at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:781)
    at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:478)
    at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:456)
    at it.corley.ant.S3GetTask.downloadFile(S3GetTask.java:65)
    at it.corley.ant.S3GetTask.execute(S3GetTask.java:39)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by wiicode** [comment]
Turns out this was 6 degrees of separation. I had a problem, then caused this one.. This problem was exactly as stated: file not found :)
